name: "Dev Branch Workflow"
on:
  workflow_call:
    secrets:
      FIREBASE_CI_TOKEN:
        required: true

jobs:
  deployApkDev:
    name: 'Upload App to Firebase Distribution'
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
      - name: "Upload app to Firebase App Distribution using Gradlew"
        env:
          FIREBASE_CI_TOKEN: ${{ secrets.FIREBASE_CI_TOKEN }}
        run: |
          ls
          export FIREBASE_TOKEN=$FIREBASE_CI_TOKEN
          ./gradlew assembleDevRelease appDistributionUploadDevRelease
#      - name: Upload App to Firebase App Distribution
#        env:
#          GOOGLE_CREDENTIAL_FILE_CONTENT: ${{ secrets.GOOGLE_CREDENTIAL_FILE_CONTENT }}
#          GOOGLE_CREDENTIAL_FILE_URL: ${{ secrets.GOOGLE_CREDENTIAL_FILE_URL }}
#          FIREBASE_APP_ID: ${{ vars.FIREBASE_APP_ID }}
#        uses: wzieba/Firebase-Distribution-Github-Action@v1
#        with:
#          appId: $FIREBASE_APP_ID
#          serviceCredentialsFileContent: $GOOGLE_CREDENTIAL_FILE_CONTENT
#          groups: internal
#          file: app/build/outputs/apk/dev/release/app-dev-release.apk