name: "Feature Branch Workflow"
on:
  push:
    branches:
      - "feature/*"
      - "bugfix/*"
      - "hotfix/*"

jobs:
  reuse-job:
    uses: ./.github/workflows/buildApkDev.yaml
    secrets:
      keystoreAliasPassword: ${{ secrets.KEYSTORE_ALIAS_PASSWORD }}
      keystorePassword: ${{ secrets.KEYSTORE_PASSWORD }}