name: "Feature Branch Workflow"
on:
  push:
    branches:
      - "tes/*"
#      - "feature/*"
#      - "bugfix/*"
#      - "hotfix/*"

jobs:
  buildApkDev:
    name: 'Build APK Development'
    uses: ./.github/workflows/buildApkDev.yaml
    with:
      KEYSTORE_ALIAS: ${{ vars.KEYSTORE_ALIAS }}
      FIREBASE_APP_ID: ${{ vars.FIREBASE_APP_ID }}
      FIREBASE_DISTRIBUTION_GROUPS: ${{ vars.FIREBASE_DISTRIBUTION_GROUPS }}
    secrets:
      BASE64_KEYSTORE: ${{ secrets.BASE64_KEYSTORE }}
      KEYSTORE_ALIAS_PASSWORD: ${{ secrets.KEYSTORE_ALIAS_PASSWORD }}
      KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      GOOGLE_CREDENTIAL_FILE_CONTENT: ${{ secrets.GOOGLE_CREDENTIAL_FILE_CONTENT }}