on:
  push:
    branches:
      - "feature/*"
      - "bugfix/*"
      - "hotfix/*"
name: "Build Dev APK"

jobs:
  buildApkDev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create Signing Properties
        env:
          KEYSTORE_ALIAS: ${{ vars.KEYSTORE_ALIAS }}
        run: |
          echo ${{ secrets.BASE64_KEYSTORE }} | base64 -d > keystore.jks
          ls
          echo "" > signing.properties
          ls
          echo "keyAlias=${{ vars.KEYSTORE_ALIAS }}" >> signing.properties
          cat signing.properties